### ISSUE TITLE
Translation - Key Concepts - blockchain

### ISSUE THREAD

**Issue by wadelu** [HyperledgerCN/fabric-docs-i18n#12]

**Comment by lujjiang** [comment]
fabric-docs-i18n/fabric-1.1.0/zh-CN/docs/source/blockchain.rst

**Comment by JulienGuo** [comment]
https://github.com/HyperledgerCN/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/blockchain.rst

**Comment by wadelu** [comment]
Done, needs review.
