### ISSUE TITLE
Translation - Key Concepts - fabric_model

### ISSUE THREAD

**Issue by lujjiang** [HyperledgerCN/fabric-docs-i18n#32]
https://github.com/HyperledgerCN/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/fabric_model.rst

**Comment by arnoldleung1112** [comment]
can i pick this translation task up? thanks

**Comment by lujjiang** [comment]
@arnoldleung1112 go ahead

**Comment by arnoldleung1112** [comment]
http://arnold-fabric-docs-i18n.readthedocs.io/en/latest/fabric_model.html#id3

please review
