### ISSUE TITLE
Translation - Tutorials - chaincode

### ISSUE THREAD

**Issue by lujjiang** [HyperledgerCN/fabric-docs-i18n#40]
https://github.com/HyperledgerCN/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/smartcontract.rst

&&&&&

https://github.com/HyperledgerCN/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/chaincode.rst

**Comment by Vicky-w** [comment]
https://github.com/Vicky-w/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/smartcontract.rst

&&&&&

https://github.com/Vicky-w/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/chaincode.rst
