### ISSUE TITLE
first four pages (index, getting_started, prereqs, samples)

### ISSUE THREAD

**Issue by Yimeng217** [HyperledgerCN/fabric-docs-i18n#5]
I am translating the following four rst documents (corresponding webpages are listed):
1. index.rst (http://fabric-docs-i18n.readthedocs.io/zh/fabric-1.1.0_zh-cn/index.html)
2. getting_started.rst (http://fabric-docs-i18n.readthedocs.io/zh/fabric-1.1.0_zh-cn/getting_started.html)
3. prereqs.rst (http://fabric-docs-i18n.readthedocs.io/zh/fabric-1.1.0_zh-cn/prereqs.html)
4. samples.rst (http://fabric-docs-i18n.readthedocs.io/zh/fabric-1.1.0_zh-cn/samples.html)

**Comment by Yimeng217** [comment]
#6

**Comment by lujjiang** [comment]
This works done, close the issue
