### ISSUE TITLE
Translation - Commands Reference » peer command : [section] Description

### ISSUE THREAD

**Issue by lujjiang** [HyperledgerCN/fabric-docs-i18n#63]
https://github.com/HyperledgerCN/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/commands/peercommand.md

**Comment by JulienGuo** [comment]
https://github.com/HyperledgerCN/fabric-docs-i18n/blob/fabric-1.1.0_zh-CN/source/commands/peercommand.md
